#!/usr/bin/env python3
"""Generate CREDITS.md from tools/asset_manifest.json + pilot files.

The pilot racers (cheetah, dog, snail, bugatti, f22) were fetched before the
manifest existed, so we re-query Commons for their license metadata here.
"""
import json, sys, urllib.parse
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.fetch_assets import image_metadata, REPO, MANIFEST

# (racer_id, field, commons_filename)
PILOT_ASSETS = [
    ('cheetah', 'image', 'File:Male_cheetah_facing_left_in_South_Africa.jpg'),
    ('cheetah', 'audio', 'File:Acoustic-Structure-and-Contextual-Use-of-Calls-by-Captive-Male-and-Female-Cheetahs-(Acinonyx-pone.0158546.s001.oga'),
    ('dog',     'image', 'File:Huskiesatrest.jpg'),
    ('dog',     'audio', 'File:Barking_of_a_dog.ogg'),
    ('snail',   'image', 'File:Snail.jpg'),
    ('bugatti', 'image', 'File:Bugatti_Chiron_1.jpg'),
    ('bugatti', 'audio', 'File:Jaguar_XJR12_(1990).ogg'),
    ('f22',     'image', 'File:F-22_Raptor_edit1_(cropped).jpg'),
    ('f22',     'audio', 'File:WWS_SaabJ35DDraken8211passingtwotimes.ogg'),
]

PILOT_EN = {'cheetah':'Cheetah','dog':'Dog','snail':'Snail','bugatti':'Bugatti','f22':'F-22 Raptor'}

manifest = json.loads(MANIFEST.read_text())

# Backfill pilot entries
for racer_id, field, cfile in PILOT_ASSETS:
    entry = manifest.setdefault(racer_id, {'en': PILOT_EN[racer_id]})
    if field in entry:
        continue  # already captured
    print(f"looking up {cfile}...")
    meta = image_metadata(cfile)  # works for any File: namespace item
    meta['source_page'] = f"https://commons.wikimedia.org/wiki/{urllib.parse.quote(cfile)}"
    entry[field] = meta
    entry.setdefault('en', PILOT_EN[racer_id])

MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))

# Sort order matches the ANIMALS array (fastest → slowest) — read racer ids
# from gen_data.py
from tools.gen_data import RACERS
order = [r[0] for r in RACERS]

def clean_author(s: str) -> str:
    """Strip HTML and trim."""
    import re
    s = re.sub(r'<[^>]+>', '', s or '')
    s = re.sub(r'\s+', ' ', s).strip()
    return s or 'Unknown'

def row(racer_id: str, kind: str, entry: dict) -> str:
    asset = entry.get(kind, {})
    lic = asset.get('license') or 'Unknown'
    author = clean_author(asset.get('author', ''))
    page = asset.get('source_page', '')
    return f"| `{racer_id}` | {kind} | {lic} | {author} | [Commons]({page}) |"

lines = [
    "# Credits",
    "",
    "All images and sounds in this project are from **Wikimedia Commons** and",
    "are licensed under the terms shown below. Each row links to the file's",
    "Commons page where the full licence text, author, and derivative-work",
    "details are available.",
    "",
    "Most files are either **Public Domain**, **CC0**, or **CC BY / CC BY-SA**",
    "(Creative Commons Attribution, possibly with ShareAlike). If you reuse",
    "this project, keep the attribution intact and share modified derivative",
    "works under the same terms where ShareAlike applies.",
    "",
    "## animal-race",
    "",
    "| Racer | Asset | Licence | Author | Source |",
    "|---|---|---|---|---|",
]
for racer_id in order:
    entry = manifest.get(racer_id, {})
    if 'image' in entry:
        lines.append(row(racer_id, 'image', entry))
    if 'audio' in entry:
        lines.append(row(racer_id, 'audio', entry))

lines.append("")
lines.append("---")
lines.append("")
lines.append("Generated by `tools/gen_credits.py` from `tools/asset_manifest.json`.")
lines.append("Re-run after refreshing assets to keep attributions up to date.")
lines.append("")

(REPO / "CREDITS.md").write_text("\n".join(lines))
print(f"Wrote CREDITS.md — {sum(1 for l in lines if l.startswith('| `'))} rows")
